### ISSUE TITLE
Wrong sort when enabled pagination

### ISSUE THREAD

**Issue by MaksimKiselev** [kotchuprik/yii2-sortable-widgets#12]
С пагинацией криво сортирует, так и задумано, что виджет можно использовать только без пагинации?

**Comment by chuprik** [comment]
Ага, а как с пагинацией должно сортировать?) Я не представляю варианта, как можно элемент со второй страницы перекинуть на первую :)

**Comment by kotchuprik** [comment]
Ага, а как с пагинацией должно сортировать?) Я не представляю варианта, как можно элемент со второй страницы перекинуть на первую :)

**Comment by MaksimKiselev** [comment]
@kotchuprik ~~у "конкурентов" himiklab/yii2-sortable-grid-view-widget нормально сортирует и на второй странице.~~
UPD Я по началу SORT_DESC поставил, от того вообще всё криво робило.

Но в обоих вариантах стреляют 100500 запросов в БД и сортировка по типу SORT_ASC идет, что очень не удобно при вставке же надо все старые обновить, а если это записей 500 допустим...

**Comment by MaksimKiselev** [comment]
А элементы очень надо было бы перекидывать, допустим сделать поле сортировки редактируемым, и агонь, задал позицию 1 будучи на 100500 странице, а оно тебе и перекинуло и сортировку не сбило.

**Comment by vsivsivsi** [comment]
Когда-то в Joomla у каждого поля были стрелочки вверх и вниз, по нажатию на которые запись "подымалась" или "опускалась" в списке. Возможно, этот вариант смог бы решить проблему сортировки с включенной пагинацией.

**Comment by MaksimKiselev** [comment]
@vsivsivsi я использую https://github.com/yii2tech/ar-position и обёртку над рубахой, написать не сложно, поддерживать просто.

`тут был ататат`

**Comment by chuprik** [comment]
@vsivsivsi ну нет, на такое я не пойду :)

@MKiselev гуд, но про это лучше писать в другом месте ))

**Comment by akorinek** [comment]
This change breaks my code, I have set pagination =false in my dataProvider

This is the problematic line (in Column.php line 30):

$offset = $this->grid->dataProvider->pagination->pageSize * $this->grid->dataProvider->pagination->page;

**Comment by chuprik** [comment]
@akorinek okay, will check tomorrow

**Comment by chuprik** [comment]
@akorinek could you check the last release?

**Comment by akorinek** [comment]
Yes, this fixes the issue, thanks.
