### ISSUE TITLE
How update GridView after ajax?

### ISSUE THREAD

**Issue by ignatenkovnikita** [kotchuprik/yii2-sortable-widgets#15]
Ка можно обновить gridView после сортировки ?

**Comment by chuprik** [comment]
http://stackoverflow.com/questions/40262338/yii2-update-the-dataprovider-of-a-listview-after-ajax

Копать в эту сторону. Если кратко — это про PJAX и обновление контейнера

**Comment by ignatenkovnikita** [comment]
ага туда и копаю
спасибо
