### ISSUE TITLE
way to make order field always start from zero vs. increment from highest order record

### ISSUE THREAD

**Issue by arievanden** [kotchuprik/yii2-sortable-widgets#22]
I wanted new records to be indexed by other owners (like "group_id") to always start from 0 instead of [$this->owner->{$this->orderAttribute} = $last->{$this->orderAttribute} + 1;]. I found that if I removed the public function behaviors(){...} from my MODEL and it prevented this behavior because it bypasses the beforeInsert() in the Sortable class. Just thought I'd share. Nice widget though.

So it looks like this:
id,group_id,order
- 1,1,0
- 2,1,1
- 3,1,2
- 4,1,3
- 5,2,0
- 6,2,1
- 7,2,2
- 8,2,3

**Comment by chuprik** [comment]
@arievanden thanks for the issue, will check and write you a question :)
