### ISSUE TITLE
Willl this work for table with composite key? 

### ISSUE THREAD

**Issue by Legion112** [kotchuprik/yii2-sortable-widgets#23]

**Comment by chuprik** [comment]
hmmm, good question :) could you send me your CREATE TABLE?

@nismangulov please, take a look at this issue :)

**Comment by chuprik** [comment]
@Legion112

**Comment by Legion112** [comment]
Excuse me. I have created my own implementation without any widget. Cos I needed drag and drop on an only specific column.

@kotchuprik
