### ISSUE TITLE
checkbox states when sorting rows

### ISSUE THREAD

**Issue by arievanden** [kotchuprik/yii2-sortable-widgets#26]
Hello. Thank you for maintaining your plugin. I use it on my site in a few places and very useful.

I have an issue that I can't figure out. I have a Gridview widget that contains checkboxes in each row like:

`'value' => function ($model, $key, $index, $grid) {
$mid = $model->_id.'_'.$model->key;
$chkbox = "<input id='{$mid}' class='selections' type='checkbox' name='selections[]' value='{$mid}'>";
                        return $chkbox;
                    },`

The strange behavior can be reproduced by:
1. selecting row checkboxes
2. de-select them
3. drag a few to re-order
4. result: the de-selected checkboxes will be selected again

It's kind of strange, but I'm not sure how to approach a fix. I tried to reproduce it on other jQuery based drag-sort examples, but can't reproduce. Do you have any ideas?

Thank you!

**Comment by chuprik** [comment]
hey Arie, could you post еру code that will show me the problem? I think grid initialization is enough.

btw, the plugin uses this library https://github.com/SortableJS/Sortable

**Comment by arievanden** [comment]
[sort_control_example.zip](https://github.com/kotchuprik/yii2-sortable-widgets/files/5824506/sort_control_example.zip)
Here's a distilled version of the page. I don't show any cookies tracking selections to re-insert. I assume it may be a browser/ui quirk, but I'm just not sure. Generally it's handy to have a form remember selections for you, but if you de-select them you expect them to stay de-selected. Tried on FF and Chrome to the same effect.

**Comment by chuprik** [comment]
@arievanden hey, updated sortablejs version, should be ok now, could you check the new version of this plugin and let me know about any issues?

**Comment by arievanden** [comment]
It looks like Sortable 1.13.0 corrected it. Thank for the update! Really appreciate it.

**Comment by arievanden** [comment]
composer package still pulls //cdn.jsdelivr.net/npm/sortablejs@1.6.1/Sortable.min.js, but I can manually update. Would be great to get Packagist updated too.

**Comment by chuprik** [comment]
@arievanden did you update the plugin version in your composer files (json and lock)?

**Comment by arievanden** [comment]
Yes, it's using wildcard. If it works for you, it'll probably work for me eventually. Might be a caching thing.

**Comment by chuprik** [comment]
@arievanden you will find installed versions in the .lock file.
