### ISSUE TITLE
Doesn`t load Sortable.min.js

### ISSUE THREAD

**Issue by kratkar** [kotchuprik/yii2-sortable-widgets#28]
See my comment https://github.com/kotchuprik/yii2-sortable-widgets/commit/fc77dafe4a04997df0505d54bbaccc83bd0bb446#r51330570

**Comment by chuprik** [comment]
@kratkar hey, thanks. do you have time to do a fork and send me a pull request?

**Comment by kratkar** [comment]
@kotchuprik Hi! Unfortunately, no. I didn't configured github after reinstalling OS.

**Comment by Fellzo** [comment]
@kotchuprik Fixed in https://github.com/kotchuprik/yii2-sortable-widgets/pull/29

**Comment by chuprik** [comment]
thank you guys. just released https://github.com/kotchuprik/yii2-sortable-widgets/releases/tag/v2.2.0
