### ISSUE TITLE
Sorting isn't saved in database

### ISSUE THREAD

**Issue by beatep** [kotchuprik/yii2-sortable-widgets#5]
I'm not sure if it's a bug or my fault, but my order isn't saved to database.

This is my code:
http://www.yiiframework.com/forum/index.php/topic/71151-sortable-gridview/
And maybe I have found what is the problem: in the console the POST request looks like
`sorting[]  1
sorting[]   0
sorting[]   2`

so the id is missing as key, but I don't know how to fix this? I'm using yii 2.0.8.

![yii2-sortable](https://cloud.githubusercontent.com/assets/1794446/15912079/b0ad73d2-2dd2-11e6-8c1e-0b9249de8d2c.png)

**Comment by chuprik** [comment]
hello, have you used my column class? and additional question, can you show how you created `dataProvidel`? it's ArrayDataProvider?

**Comment by chuprik** [comment]
little bit explanation:
`1`, `0`, `2` from your screen, should be ID of models, no keys is correct values. 
what ID you have in your CRUD? could you look `data-id` attribute in Sortable column?

**Comment by beatep** [comment]
Thanks for your quick answer.

Yes, I used your column class. My dataProvider is an ArrayDataProvider:
`$dataProvider = new ArrayDataProvider([
        'allModels' => $model->kapitel,
        'sort' => [
            'attributes' => ['id', 'username', 'email'],
        ],
        'pagination' => [
            'pageSize' => 10,
        ],
    ]);`

But 1,0,2 is not the id of my models, it's the new sorting order. How does the update method know, which id is concerned?
This is how my table column looks like...
![d](https://cloud.githubusercontent.com/assets/1794446/15923251/7c50308e-2e2c-11e6-97aa-27bb414dec28.png)

**Comment by beatep** [comment]
Why I thought the ID is missing: This is how the sorting in my yii1 grid worked.
![yii1](https://cloud.githubusercontent.com/assets/1794446/15923384/43befc2c-2e2d-11e6-8167-6d00e9fc19a2.png)

**Comment by chuprik** [comment]
You have used another extension for yii1. I did another approach. So, I will check this problem today and will be back to you.

**Comment by beatep** [comment]
Did you find out enything?

**Comment by chuprik** [comment]
hello, yes. could you change https://github.com/kotchuprik/yii2-sortable-widgets/blob/master/assets/files/js/sortable-widgets.js#L5 to `data-id` in your local file? and check sorting again?

**Comment by beatep** [comment]
Nothing has changed, sorry (I think I already tested that).

**Comment by chuprik** [comment]
could you to do composer update, add `rowOptions` and check again? I've found problem with using `ArrayDataProvider`

**Comment by babib2** [comment]
Explain to me please. I can not sort the list. But when I add a parameter in the query string                     ?sort=order, then the list is sorted. Where this option is added in the code? Like this...

```
 public function actions()
    {
        return [
            'sorting' => [
                'class' => \kotchuprik\sortable\actions\Sorting::className(),
                'query' => \common\modules\test\models\Test::find()->addOrderBy('order'),
            ],
        ];
    }
```

**Comment by chuprik** [comment]
Please, look the example `addOrderBy` is no needs. What with your post request now?

**Comment by babib2** [comment]
How should work sorting?
"Order" is changed immediately when perestanoke? I only changed when to reload the page. Lines menyut its position when moving. But the value of the field does not change the order. This is when the parameter ?sort=order.

```
Request URL:http://yiistart/backend/test/test/sorting/
FORM DATA
/index/?sort=order
sorting[]:8
sorting[]:9
sorting%5B%5D=8&sorting%5B%5D=9
sorting[]:9
sorting[]:8
sorting%5B%5D=9&sorting%5B%5D=8
/index
sorting[]:8
sorting[]:9
sorting%5B%5D=8&sorting%5B%5D=9
sorting[]:9
sorting[]:8
sorting%5B%5D=9&sorting%5B%5D=8

```

**Comment by chuprik** [comment]
perestanoke, menyut — google translate RU-EN? :)

I don't understand your question. What do you want know?

You have next elements: 45, 94, 100. When you will swap 45 and 100, the extension will send:

`sorting[]: 100`
`sorting[]: 94`
`sorting[]: 45`

It means next 1st order for 100, 2nd order for 94 and 3rd order for 45. Number of position in array will be order for element.

From your example:

Before:

```
sorting[]:8
sorting[]:9
```

After:

```
sorting[]:9
sorting[]:8
```

It means that you have swapped 8 and 9. New order for 9 will be 1, for 8 will be 2.

**Comment by babib2** [comment]
I want to say that I have retained only if the permutation of the query string is the next attribute 
?sort=order.
That is, I do sort by order.
A value in the column "order" changes only when you restart the page

**Comment by beatep** [comment]
yes, now it works! Thank you 👍

**Comment by chuprik** [comment]
awesome :)
